### ISSUE TITLE
More of a patch...

### ISSUE THREAD

**Issue by mrgreen3** [CarlDuff/aif#6]
Could you add the following too aif

# Adapted from AIS. An excellent bit of code!
arch_chroot() {
    # to make aif work under ArchBang live
    # for some reason udev fails to umount correctly during arch-chroot
    [[ $(mount | grep "udev") ]] && umount -l udev
    arch-chroot $MOUNTPOINT /bin/bash -c "${1}"
} 

The test was the only way I could get aif to work under ArchBang live and it does work. Once added I will create script to pull in aif then create live iso (autumn release)

**Comment by CarlDuff** [comment]
Although I don't mind other - unrelated - distros using the Architect installer, I'm afraid I must draw the line at purposely patching it for that purpose. Especially as it would incur additional testing on my part to ensure proper functionality for my project.

I would advise utilising a sed command or something in the initialisation script to make the desired changes before executing the installer.
