### ISSUE TITLE
Support NVMe Devices

### ISSUE THREAD

**Issue by jcarvalho** [CarlDuff/aif#7]
On Arch, NVMe devices (like the Samsung 950 Pro) are mapped under `/dev/nvmeXXX` (in my case, `/dev/nvme0n1`.

This means that the devices are never shown on the device list for the partitioning step. On the mounting step, partitions for those devices are shown, but their mounting always fails.

I was able to perform a full install by simply adding `nvme\` to the regexes matching for `sd`, `hd` and `vd` devices. 

However, I was unable to use the NVMe SSD as a proper boot device, as GRUB always issued an error upon boot (meaning that the Motherboard was properly recognizing the SSD and booting into it, only GRUB seemed to have compatibility issues, whether this is a bug on AIF or GRUB, I'm not sure).

As NVMe devices are getting more popular, I think it's important for AIF to properly support them.

If you wish, I can submit a PR with the changeset that allowed me to install my system, even though NVMe boot isn't properly tested.

**Comment by CarlDuff** [comment]
Yes, please - and thanks for the info!

**Comment by CarlDuff** [comment]
Fixed and closed. Thanks for the feedback!
